### ISSUE TITLE
cannot running the bat file

### ISSUE THREAD

**Issue by DRAMA22** [JouriM66/DPF.Android.Native.Components#2]
Solved

**Comment by DRAMA22** [comment]
ok i added " " EMBO_DEX Path now stuck into another error
ERROR: error compiling java sources. Try to set verbose mode.

**Comment by DRAMA22** [comment]
spend whole day couldnt get it to work on seattle 

Configuring...
Compiling the Java Sources...
Creating jar containing the new classes...
Converting from jar to dex...
Merging dex files...
Exception in thread "main" com.android.dex.DexException: unknown output extensio
n: project\Rad
        at com.android.dex.Dex.<init>(Dex.java:115)
        at com.android.dx.merge.DexMerger.main(DexMerger.java:1119)

Could Not Find E:\DPF.Android.Native.
Components-master\DPF.Android.Native.Components-master\JavaClasses\output\dex\te
st_classes.dex
Copy created classes to ".\Classes\classes.dex"
The system cannot find the file specified.
All done!
Do not forget to read "Install.txt" to usage instructions
Good luck :)
Press any key to continue . . .
